version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3008:80"
    volumes:
      - /home/booskit/web/faction.booskit.dev/private/fp-data:/var/www/html/storage
    env_file:
      - stack.env # Pulls variables defined in the Portainer UI
    extra_hosts:
      - "host.docker.internal:host-gateway" # Creates a DNS route from the container to your host machine

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3007:80"
    env_file:
      - stack.env
    depends_on:
      - backend